steps:
  - name: node
    entrypoint: npm
    args: ['install']
    dir: 'frontend'
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - 'REACT_APP_API_KEY=${_API_KEY}'
  - name: node
    entrypoint: npm
    args: ['run', 'build']
    dir: 'frontend'
  - name: gcr.io/step-34-2020/firebase
    args: ['deploy', '--project=step-34-2020', '--only=hosting']
    dir: 'frontend'
