steps:
  - name: node
    entrypoint: npm
    args: ['install', 'run', 'build']
    dir: 'frontend'
  - name: gcr.io/step-34-2020/firebase
    args: ['deploy', '--project=step-34-2020', '--only=hosting']
    dir: 'frontend'
